baseURL = "https://example.com"
title = "Yossy's Notes"
languageCode = "ja"
theme = ["docsy"]

# 言語設定
defaultContentLanguage = "ja"
[languages]
[languages.ja]
title = "Yossy's Notes"
description = "〜 学んだことを随時更新しています。 〜"
languageName = "日本語"
weight = 1
[languages.ja.params]
description = "日本語の説明"

# Docsyテーマの設定
[params]
copyright = "Your Name"
privacy_policy = "https://policies.google.com/privacy"

# 右側のサイドバーの目次
[params.ui]
sidebar_menu_compact = true
sidebar_menu_foldable = true
sidebar_cache_limit = 10

# 検索機能の有効化
[params.ui.search]
enabled = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name_key = "community_x_name"
	url = "https://x.com/yoshihiro_shu"
	icon = "fab fa-twitter"
# Replace with fa-x-twitter once available

[[params.links.developer]]
	name_key = "community_github_name"
	url = "https://github.com/yoshihiro-shu"
	icon = "fab fa-github"

# ナビゲーションバーの設定
[menu]
[[menu.main]]
  name = "ドキュメント"
  weight = 1
  url = "/docs/"
[[menu.main]]
  name = "ブログ"
  weight = 2
  url = "/blog/"
[[menu.main]]
  name = "お問い合わせ"
  weight = 3
  url = "https://docs.google.com/forms/d/e/1FAIpQLSeWO6HmGM87-AWIOEOZ0Dff9grPRfkfFgQXPLXVA6YwjbPQBg/viewform"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false # Required for dark-mode
