[build]
  command = "cd themes/docsy && git submodule update -f --init && cd ../.. && hugo"
  publish = "public"

[build.environment]
NODE_VERSION = "20.17.0"
GO_VERSION="1.23.1"
HUGO_VERSION = "0.136.5"
