[build]
  command = "git submodule update --init --recursive --depth 1 && cd themes/docsy && cd ../.. && hugo"
  publish = "public"

[build.environment]
NODE_VERSION = "20.17.0"
# GO_VERSION="go1.23.1"
HUGO_VERSION = "0.136.5"
